from diffusers import StableDiffusionPipeline
import torch
import matplotlib.pyplot as plt
from pathlib import Path


def main():
    prompt = input("Enter your prompt: ").strip()
    if not prompt:
        print("Prompt cannot be empty.")
        return

    device = "cuda" if torch.cuda.is_available() else "cpu"
    dtype = torch.float16 if device == "cuda" else torch.float32

    print(f"Using device: {device}")
    pipe = StableDiffusionPipeline.from_pretrained(
        "runwayml/stable-diffusion-v1-5",
        torch_dtype=dtype,
    ).to(device)

    if device == "cuda":
        with torch.autocast("cuda"):
            image = pipe(prompt).images[0]
    else:
        image = pipe(prompt).images[0]

    output_dir = Path("results")
    output_dir.mkdir(exist_ok=True)
    output_path = output_dir / "generated_image.png"
    image.save(output_path)

    plt.imshow(image)
    plt.axis("off")
    plt.title("Generated by Stable Diffusion")
    plt.show()

    print(f"Image saved to: {output_path}")


if __name__ == "__main__":
    main()
